### ISSUE TITLE
Re-drawing elements

### ISSUE THREAD

**Issue by BlackGoku36** [armory3d/zui#104]
when trying to re-draw zui's elements that isn't a window element than it would not re-draw
eg: 
```hx
buttonHandle.redraws = 2;//Does nothing
//But
windowHandleThatContainAboveButton.redraws = 2;//Re-draws now
```
Is it supposed to work like this?

**Comment by luboslenco** [comment]
Yes, `redraws` is only applicable to window handles as of now.
