### ISSUE TITLE
[BUG] Vertical tabs bugs

### ISSUE THREAD

**Issue by BlackGoku36** [armory3d/zui#107]
* First element is not drawn
* First tab's elements's width overflow
* Second and from then tabs's elements like text input, slider's width overflow (Buttons work fine)
![Screen Recording 2020-01-17 at 11 57 45 AM](https://user-images.githubusercontent.com/36535717/72589300-dd22bf00-3920-11ea-9aeb-5ae6ed23a8d7.gif)

(Elements.hx example)

**Comment by luboslenco** [comment]
Should be better now. To also ensure the background is filled for the tab content, set `theme.FILL_WINDOW_BG` to `true`.
