### ISSUE TITLE
Several 'texParameter' errors per frame

### ISSUE THREAD

**Issue by ratkingsminion** [armory3d/zui#115]
I use git Kha and Haxe 4.0.5. Target is JS. Basically I added a zui.window to the Kha Hello World, and I get errors every frame. The program is working though, there is no error in the functionality (as far as I can see).

```
kha/graphics4/PipelineState.hx:111: Warning: Sampler tex not found.
WebGL: INVALID_OPERATION: texParameter: no texture bound to target
WebGL: INVALID_OPERATION: texParameter: no texture bound to target
<snip>
kha/js/graphics4/Graphics.hx:146: WebGL error: Invalid operation
WebGL: INVALID_OPERATION: texParameter: no texture bound to target
WebGL: INVALID_OPERATION: texParameter: no texture bound to target
WebGL: INVALID_OPERATION: texParameter: no texture bound to target
WebGL: INVALID_OPERATION: texParameter: no texture bound to target
WebGL: INVALID_OPERATION: texParameter: no texture bound to target
WebGL: too many errors, no more errors will be reported to the console for this context.
kha/js/graphics4/Graphics.hx:146: WebGL error: Invalid operation
kha/js/graphics4/Graphics.hx:146: WebGL error: Invalid operation
kha/js/graphics4/Graphics.hx:146: WebGL error: Invalid operation
<snip>
```

**Comment by sh-dave** [comment]
If you don't need a bleeding edge Kha version, you could temporarily revert back to https://github.com/Kode/Kha/commit/fe6c33248a2283a627248bc2d2d23d2eb6238abd as a workaround.

**Comment by ratkingsminion** [comment]
Thank you! I mainly wanted to know if this was a configuration error on my part.

**Comment by sh-dave** [comment]
It seem the commit was reverted now (https://github.com/Kode/Kha/commit/fbf2aa39f5a576e43c386b2c26d0106f021b64b6 / https://github.com/Kode/Kha/issues/1177), can you check if this also fixes your issue?

**Comment by ratkingsminion** [comment]
Yes, that fixed it. The only warning remaining is "kha/graphics4/PipelineState.hx:111: Warning: Sampler tex not found.", but I know that one is safe to ignore.
