### ISSUE TITLE
Clearing issue on native macos build (metal)

### ISSUE THREAD

**Issue by BlackGoku36** [armory3d/zui#123]
The background of window element is not 'cleared'.

Elements example:
<img width="512" alt="Screen Shot 2020-07-13 at 12 22 45 AM" src="https://user-images.githubusercontent.com/36535717/87254260-fa36e580-c49e-11ea-8ba5-b7d65d2eb5d8.png">

More horrible clearing issue:
<img width="1174" alt="Screen Shot 2020-07-13 at 12 29 22 AM" src="https://user-images.githubusercontent.com/36535717/87254412-0b342680-c4a0-11ea-888d-7259f5ad46c7.png">

**Comment by luboslenco** [comment]
See https://github.com/Kode/Kinc/issues/456 https://github.com/Kode/Kha/issues/925.
