### ISSUE TITLE
Improve TextArea performance

### ISSUE THREAD

**Issue by mundusnine** [armory3d/zui#124]
Right now how the rendering of text for the text area works is we render every line of text supplied by the user which makes it so that even text that isnt visible renders which impacts performance when we have long text files.

**Comment by luboslenco** [comment]
Elements which are not visible should never render in zui. Is it not behaving that way?

**Comment by mundusnine** [comment]
Maybe its not the rendering but the for loop of the textArea that makes it linear/slow ? i.e.: [here](https://github.com/armory3d/zui/blob/master/Sources/zui/Ext.hx#L400)

**Comment by luboslenco** [comment]
Aha so you are already experiencing bad perf, will investigate then!

**Comment by mundusnine** [comment]
So I tried recreating the bug on my end to see if the perf issues where really related to the textarea. So I tested with a big big file without issues 11000 lines. So this can be closed. Sorry for the trouble. Was probably something on my end and I thought that the textarea rendering was the cause because of its linearity.
