### ISSUE TITLE
textInput doesn't trigger the virtual keyboard on mobile browsers

### ISSUE THREAD

**Issue by tcdude** [armory3d/zui#128]
I'm not sure if this is even possible, but using Kha's HTML5 target, the textInput widget doesn't trigger the virtual keyboard if used in a browser on mobile (tested on Android in Chrome and Firefox).

**Comment by luboslenco** [comment]
Hello, the keyboard show-up in Zui is handled via:
https://github.com/armory3d/zui/blob/master/Sources/zui/Zui.hx#L740

Which then for Kore backend resolves to:
https://github.com/Kode/Kha/blob/master/Backends/Kore/kha/kore/Keyboard.hx

So for HTML5 it would be the best to implement it in the Kha backend as well, not directly in Zui.
https://github.com/Kode/Kha/tree/master/Backends/HTML5/kha

Not sure if it's possible either but I assume there is always a way. 🙂
