### ISSUE TITLE
Add a way to implement custom nodes

### ISSUE THREAD

**Issue by mundusnine** [armory3d/zui#134]
Add ability to create something like: 

![image](https://user-images.githubusercontent.com/29337013/101526358-7ce2a480-395a-11eb-86ba-3b208c6f88f2.png)

with custom rendering.

**Comment by luboslenco** [comment]
Should be doable now via https://github.com/armory3d/zui/commit/7cac2c6182c17142f4c272ca841752db7c17604d.

Node definition:
```hx
{
	id: 0,
	name: "My Node",
	type: "MY_NODE",
	x: 0,
	y: 0,
	color: 0xffb34f5a,
	inputs: [],
	outputs: [
		{
			id: 0,
			node_id: 0,
			name: "Value",
			type: "VALUE",
			color: 0xffa1a1a1,
			default_value: 0.5
		}
	],
	buttons: [
		{
			name: "hello.World.myNodeButton",
			type: "CUSTOM",
			height: 1
		}
	]
}
```

Custom button drawing:
```hx
package hello;
class World {
	public static function myNodeButton(ui: Zui, nodes: Nodes, node: TNode) {
		ui.button("My Button");
	}
}
```

ArmorPaint example:
https://github.com/armory3d/armorpaint/blob/master/Libraries/shaderlib/Sources/arm/shader/NodesMaterial.hx#L1840
https://github.com/armory3d/armorpaint/blob/master/Libraries/shaderlib/Sources/arm/shader/NodesMaterial.hx#L2292
