### ISSUE TITLE
Question about Nodes API

### ISSUE THREAD

**Issue by flamendless** [armory3d/zui#137]
Hi, Im starting to use this lib for a software project and im looking forward to fully using it as I want to also make a project using Haxe.

* Is there an API for changing the name of a node when the title field is clicked?
* What's the method/way to determine if a node is clicked or selected by the mouse?
* What are the `types` available aside from `"VALUE"`?

**Comment by luboslenco** [comment]
Hi, sorry about  the delay.

> Is there an API for changing the name of a node when the title field is clicked?

I have added `onHeaderReleased` callback to tell when the node title field has been clicked
https://github.com/armory3d/zui/blob/master/Sources/zui/Nodes.hx#L38

> What's the method/way to determine if a node is clicked or selected by the mouse?

`Nodes.nodesSelected`
https://github.com/armory3d/zui/blob/master/Sources/zui/Nodes.hx#L9

> What are the types available aside from "VALUE"?

For buttons: https://github.com/armory3d/zui/blob/master/Sources/zui/Nodes.hx#L567
For inputs / outputs: https://github.com/armory3d/zui/blob/master/Sources/zui/Nodes.hx#L653
Custom: https://github.com/armory3d/zui/issues/134
