### ISSUE TITLE
isHovered only returns true when hovering over the last element.

### ISSUE THREAD

**Issue by jackwlee01** [armory3d/zui#142]
I might be not understanding how to use isHovered properly, but it seems it is only returning true when the cursor is hovering over the last element (and not the whole window).

**Comment by luboslenco** [comment]
Hello, thanks for report. Check the example at https://github.com/armory3d/zui/blob/master/examples/Elements/Sources/Elements.hx#L33, it should work for non-last elements as well.

**Comment by jackwlee01** [comment]
Ah I see, I thought I could check isHovered for the entire window. Is there a way to do that?
