### ISSUE TITLE
MultipleWindows example does not compile

### ISSUE THREAD

**Issue by Jillinger** [armory3d/zui#160]
Just downloaded and tried the Elements example.
There was an error made at line 1200 in Zui.hx.
I fixed it with 
```
catch (e:Any) {
	trace(Std.string(e));
}
```

**Comment by Jillinger** [comment]
There appears to be another error in the MultipleWindows example Main.hx line 4
No namespace kha.WindowOptions.Position exists.

I'm not sure what's rhe best option for fixing this one. Position.hx is found many place. Haxe seems to be the most practical source.

Should I create a WindowOptions directory in "...zui\examples\Kha\Sources\kha", and copy the Position module from haxe - C:\haxe\std\haxe\display\Position.hx, or should I add haxe as a library to the khafile?

**Comment by luboslenco** [comment]
I have removed the MultipleWindows example, I am not sure what is the state of supporting that in Kha nowadays. Thanks for notice.

**Comment by rpaladin** [comment]
I think it was moved over to Kinc? https://github.com/Kode/Kinc-Samples/tree/main/MultiWindow
