### ISSUE TITLE
color_wheel not working

### ISSUE THREAD

**Issue by t3du** [armory3d/zui#161]
color wheel is not working because this img can not be found:

ui.image(ui.ops.black_white_gradient);

if i comment this line and replace it with ui.image(ui.ops.color_wheel, kha.Color.fromFloats(cval, cval, cval));  it works.

i tried to add the image to the folder but it seems either im doing it wrong or is not working.

**Comment by luboslenco** [comment]
Added at https://github.com/armory3d/zui/commit/a7754de1704ac0bb8fb934c969eae2284729fe58, thanks for notice.

**Comment by t3du** [comment]
thanks lubos but it seems it does not fix the issue. i was using zui from armory3d using the ext.hx file calling color_wheel from a ui trait... i downloaded the new zui directory with the fix but i have the same problem. My file worked before this new implementation of the color gradient image. Im experimenting with a node for armory to make available the color picker as a node.

**Comment by rpaladin** [comment]
@t3du did you by chance forget to clear your project's `cache`?

**Comment by t3du** [comment]
No sadly, i constantly delete it in order to be sure it doesn't interfere. Maybe we could confirm the issue if anyone else has this problem. For me i could bypass it doing what i did.
