### ISSUE TITLE
Deprecation warning for kha.graphics2.GraphicsExtension

### ISSUE THREAD

**Issue by MoritzBrueckner** [armory3d/zui#163]
See https://github.com/armory3d/armory/issues/2868, this likely needs to be fixed in Zui since `GraphicsExtension` is used in [Nodes.hx](https://github.com/armory3d/zui/blob/946848c8f3a688b889a7b31b06517a03c22238d8/Sources/zui/Nodes.hx#L3). @ luboslenco please let me know if we instead should add it to Armory (the warnings will still occur with Nodes.hx then).

**Comment by luboslenco** [comment]
Thanks for letting me know - should be fine to include `GraphicsExtension` directly in this repository then, pull request welcome.
