### ISSUE TITLE
Implement a way to check if a control was updated?

### ISSUE THREAD

**Issue by FuzzyWuzzie** [armory3d/zui#19]
A la Unity's [`BeginChangeCheck`](https://docs.unity3d.com/ScriptReference/EditorGUI.BeginChangeCheck.html):

``` c#
EditorGUI.BeginChangeCheck ();

// Block of code with controls
// that may set GUI.changed to true.

if (EditorGUI.EndChangeCheck ()) {
    // Code to execute if GUI.changed
    // was set to true inside the block of code above.
}
```

Not absolutely necessary as I can get around it by using temporary variables for now, and it might add a lot of code headache, but it would certainly be handy for me.

**Comment by luboslenco** [comment]
Now (finally) resolved in https://github.com/armory3d/zui/issues/32.

**Comment by FuzzyWuzzie** [comment]
Awesome, thanks!
