### ISSUE TITLE
Bug when scrolling when have more then one instance of zui

### ISSUE THREAD

**Issue by romamik** [armory3d/zui#23]
If having two or more instances of zui, first instance of zui sets isScrolling to false in onMouseUp handler and other instances of zui fail to set windowStates and sliderStates 'scrolling' field to false.

**Comment by romamik** [comment]
If having two or more instances of zui a scrolling window, first instance of zui sets isScrolling to false in onMouseUp handler and other instances of zui fail to set windowStates and sliderStates scrolling field to false.

**Comment by luboslenco** [comment]
This should be fixed.
