### ISSUE TITLE
Inconsistency in window function parameters

### ISSUE THREAD

**Issue by romamik** [armory3d/zui#24]
Inconsistency in window function parameters:
x:Int, y:Int, - are in screen coordinates, not taking scaleFactor into account
w:Int, h:Int, - are in scaled coordinates, so real width and height in screen coordinates are w \* scaleFactor and h \* scaleFactor.

**Comment by luboslenco** [comment]
Fixed! https://github.com/armory3d/zui/commit/7c5e97a1462bbd6860b02ca403e83b18154b218b
