### ISSUE TITLE
Font sizes passed to Zui constructor prevent unicode glyphs rendering for text at those sizes

### ISSUE THREAD

**Issue by thoughton** [armory3d/zui#27]
As originally discussed here:
http://forum.kode.tech/topic/122/how-to-draw-unicode-characters

I've encountered an issue whereby it seems that the font sizes passed into the Zui constructor somehow prevent those particular font sizes from rendering unicode glyphs via g2.drawString calls.

I've put together a small example program here:
https://github.com/thoughton/kha-InputThing

In particular, see this code on line 20 of Project.hx in that example:

```
// Issue:
//  The font sizes passed to Zui here cause the unicode glyphs to fail to render when g.drawString is called for text of either of these sizes.
//  Changing these sizes changes the size of unicode glyphs that fail to draw.
//  Commenting out or removing this Zui instatiation will re-enable unicode glyph rendering at all font sizes. 
m_zui = new Zui(Assets.fonts.NDS12, 24, 12, 0, 1.0, 1.0);
```

Here's an image of the output using the above snippet of code:
![](https://s13.postimg.org/pyzg3q993/inputthing.png)

**Comment by luboslenco** [comment]
Fixed in https://github.com/armory3d/zui/commit/b310dab635bde1ebc8cb684d7ee5db04d1f1106b. The issue was zui touching the font file to retrieve its height before the glyphs were added.
