### ISSUE TITLE
Custom skins

### ISSUE THREAD

**Issue by hsdk123** [armory3d/zui#34]
Hi, I was wondering if custom skinning might be possible for the widgets in zui - is this currently doable?

**Comment by luboslenco** [comment]
It is possible to some degree, but I would not recommend it yet. Theme system needs more work and that may bring breaking changes in the future.

The way it works right now is by passing [TTheme](https://github.com/armory3d/zui/blob/master/Sources/zui/Themes.hx) structure into the Zui constructor:

`var ui = new Zui({ font:Font, theme = myTheme });`

**Comment by luboslenco** [comment]
Cleaned up the theme structure, should do for now.
https://github.com/armory3d/zui/blob/master/Sources/zui/Themes.hx
