### ISSUE TITLE
zui needs updating for the latest changes to kha

### ISSUE THREAD

**Issue by lewislepton** [armory3d/zui#37]
hello zui will need changes due to the addition of `KeyCode` & `kha.Key` not existing now ;)

tried, but ran into a head scratch moments

**Comment by vlad-v** [comment]
im new to git & kha in general, although i fixed it for limited use ( 0-9,A-Z,space keys are working ) so if you need a temporary solution for now, have a look at 
https://github.com/armory3d/zui/compare/master...vlad-v:patch-1

**Comment by lewislepton** [comment]
oh cool. i was meaning to get to it after this message. i was doing a stream at the same time. but forgot to get back to it offline.
ill have a look cheers

**Comment by luboslenco** [comment]
Oh, should be fixed now.
