### ISSUE TITLE
Begin/End nesting limited

### ISSUE THREAD

**Issue by Disar** [armory3d/zui#39]
I'm passing the Zui object down into several other objects to draw their own thing. I'm trying to render to a render target like so:

		if(ui.panel(panelID,header)){
			for(m in messages.keys()){
				ui.text('${m}: ${messages[m]}');
			}
		}

		ui.separator();

		ui.end();

		fpsCanvas.g2.begin(true, 0);
		fpsPoints[0] = messages['Scene time'];

		for(i in 0...fpsPoints.length){
			fpsCanvas.g2.drawRect((200 - ratio) * i, fpsPoints[i]*60,1,1);
		}

		fpsCanvas.g2.end();

		ui.begin(); <----- problem

In this scope I do not have the g2 object and I can't call begin without pointing to a g2. To fix this I'm also passing the g2 object into the function to pass it back into the begin call.

perhaps there should be something like `continue()` considering globalG is already set.

No idea if im using it wrong.

Edit: I just realized calling end actually flushes the whole thing, any advice?

**Comment by Disar** [comment]
So i realized I should probably use Zui.g ?

**Comment by luboslenco** [comment]
If it works then `ui.g.end();` sounds ok.

**Comment by Disar** [comment]
it seems to work, but it feels weird touching the graphics state. It will do.
