### ISSUE TITLE
Set default values at runtime

### ISSUE THREAD

**Issue by tienery** [armory3d/zui#40]
While the `Id.handle()` function call is nice, it would be better if default values, or the state of a series of elements returned to "defaults" via a call such as `ui.clearCache()`.

To give an example where this would be useful, I am trying to put together a "PropertyBox" for multiple items on the game scene.

```haxe
class PropertyBox
{

	static var lastSelected:Int;

	public static function show(gui:Zui, scene:Scene)
	{
		var command = scene.commands[scene.selectedIndex];

		if (gui.panel(Id.handle(), "Properties"))
		{
			if (command.type == DRAW_LINE)
			{
				var defaultX, defaultY, defaultX2, defaultY2, defaultR, defaultG, defaultB, defaultA, defaultStrength;
				if (lastSelected != scene.selectedIndex)
				{
					defaultX = { text: "0" };
					defaultY = { text: "0" };
					defaultX2 = { text: "50" };
					defaultY2 = { text: "50" };
					defaultStrength = { text: "1" };
					defaultR = { value: 0.0 };
					defaultG = { value: 0.0 };
					defaultB = { value: 0.0 };
					defaultA = { value: 1.0 };
				}

				gui.text("First Position");
				gui.row([0.5, 0.5]);
				var x = Std.parseInt(gui.textInput(Id.handle(defaultX), "X"));
				command.x = x != null ? x : 0;
				var y = Std.parseInt(gui.textInput(Id.handle(defaultY), "Y"));
				command.y = y != null ? y : 0;

				gui.text("Second Position");
				gui.row([0.5, 0.5]);
				var x2 = Std.parseInt(gui.textInput(Id.handle(defaultX2), "X2"));
				command.x2 = x2 != null ? x2 : 50;
				var y2 = Std.parseInt(gui.textInput(Id.handle(defaultY2), "Y2"));
				command.y2 = y2 != null ? y2 : 50;

				var strength = Std.parseFloat(gui.textInput(Id.handle(defaultStrength), "Line Strength"));
				command.lineStrength = strength != null ? strength : 1;

				gui.separator();
				gui.text("Line Color");
				var red = gui.slider(Id.handle(defaultR), "R", 0, 1);
				var green = gui.slider(Id.handle(defaultG), "G", 0, 1);
				var blue = gui.slider(Id.handle(defaultB), "B", 0, 1);
				var alpha = gui.slider(Id.handle(defaultA), "A", 0, 1);
				command.color = Color.fromFloats(red, green, blue, alpha);
			}
		}

		lastSelected = scene.selectedIndex;
	}

}
```

Now, I tried using the `Id.handle` call to set defaults, but realised it's macro based and won't work at runtime. This means that if an object is added to the scene for rendering, and the PropertyBox remains at the values it was since the previously added object, the new object then takes the properties of the previous object. In a way, the newly added object shares the properties of the previous object, as long as that object is the same type.

Now, I could operate on every draw command as a separate PropertyBox, and only display the PropertyBox for the currently selected element as I iterate through each one, but that sounds like something that would slow the program down.

Ideally, what I would like to do is, within the call `if (lastSelected != scene.selectedIndex)` is do `gui.clearCache()` which would remove all states that had not been previously changed since the last frame, and be able to set default values at runtime so that the next selected object does not end up "sharing" the same properties as the previously selected object.

Is this something that can be implemented?

**Comment by sh-dave** [comment]
Why even use this default values stuff and not just pass the current values in?
```haxe
...
var x = Std.parseInt(gui.textInput(Id.handle({ text: Std.string(command.x) }), "X"));
...
```

**Comment by tienery** [comment]
I already tried doing that. Re-read my code. I could always try making it "hard-boiled" but the problem is that Zui reserves the state, which is not what I want. I need to be able to clear the state in order to prevent multiple objects from sharing the same properties.

**Comment by sh-dave** [comment]
Hm, last time i used zui it didn't cache anything. So this is basically the same issue as https://github.com/armory3d/zui/issues/33. The following should be useable as a workaround.
- create the handles manually
- update the corresponding value on the handle
- set the handle.redraw to >= 2 in case you change your data without zui input
  - (not required in the sample as you change data via the button click, so zui is redrawing
  - you might need to do that recursive in case the window doesn't redraw

```haxe
import zui.*;
import zui.Zui;

class Main {
	public static function main() {
		kha.System.init({ title : "Elements", width : 800, height : 600 }, Elements.run);
	}
}

@:structInit
private class Something {
	public var textProp: String;
	public var floatProp: Float;
}

private class Elements {
	public static function run()
		new Elements();

	var z: Zui;
	var index = 0;
	var somethings: Array<Something> = [
		{ textProp: '1st thing', floatProp: 0.5 },
		{ textProp: '2nd thing', floatProp: 0.75 },
	];

	function new()
		kha.Assets.loadEverything(setup);

	function setup() {
		z = new Zui({font: kha.Assets.fonts.DroidSans});
		kha.System.notifyOnRender(render);
	}

	static var textPropHandle = new Handle();
	static var floatPropHandle = new Handle();

	function render( fb: kha.Framebuffer ) {
		var g2 = fb.g2;

		z.begin(g2);
			var thing = somethings[index];

			if (z.window(Id.handle(), 0, 0, kha.System.windowWidth(), kha.System.windowHeight())) {
				textPropHandle.text = thing.textProp;
				thing.textProp = z.textInput(textPropHandle, 'textprop');

				floatPropHandle.value = thing.floatProp;
				thing.floatProp = z.slider(floatPropHandle, 'floatprop', 0.0, 1.0, true);

				if (z.button('next')) {
					index = ++index % 2;
				}
			}

		z.end();
	}
}

```
