### ISSUE TITLE
[Rendering]Window background different on native vs webgl

### ISSUE THREAD

**Issue by Disar** [armory3d/zui#55]
When creating a window with a panel  on webgl it looks like this :

https://i.imgur.com/MQST5AZ.png

But on windows : 

https://i.imgur.com/tw0MIeC.png

I'm assuming the windows version is the correct behavior? I'd really like to have the window to automatically adapt to the panel. Which is what happens in webgl.

```
                    ui.begin(g);
			if(ui.window(Id.handle(), 0,0,360,640,false)){
			 	panel = ui.panel(Id.handle(),'Debug Panel FPS: ${util.FPSCounter.fps}');
				if(panel){
				var check = ui.check(Id.handle(),"Allow Diagonal Matching");
					game.allowDiagonalMatching = check;

					check = ui.check(Id.handle(),"Allow Horizontal Clash");
					game.allowHorizontalClash = check;

					
					check = ui.check(Id.handle(),"Allow Synergy");
					game.allowSynergy = check;
					if(ui.button("Clear Row")){
						game.clearRow(0);
					}

					game.setSFXVolume(ui.slider(Id.handle(),"SFX Volume",0.0,1.0,true,100,true));
			}
		}
		ui.end();
```

**Comment by luboslenco** [comment]
Hm, does setting [FILL_WINDOW_BG](https://github.com/armory3d/zui/blob/master/Sources/zui/Themes.hx#L123) to `true` and [WINDOW_BG_COL](https://github.com/armory3d/zui/blob/master/Sources/zui/Themes.hx#L91) to `0x00000000` do anything?

**Comment by Disar** [comment]
Same result. At first I thought I forgot to reset the shader, but setting the pipeline to null doesn't help.

Can you confirm if works on your system?

**Comment by luboslenco** [comment]
Ah, so a D3D / OpenGL disparity in Kha? Or maybe zui doing some undefined behaviour stuff. OpenGL and WebGL work ok here(window not filled), will also try D3D later on Windows.

**Comment by Disar** [comment]
At first I thought it was an issue with parsing shader/material data from json. As clockwise/counterclock wise are reversed depending on the system I'm on. More specifically for opengl I flip the y component of the projection matrix so things are rendered upside down to make it look correct, this also reverses the winding of the meshes.

However considering I do set the pipeline to null, also specifically set the g.begin(false)/g.end I don't think it's anything I've tried.

Must be disparity between the platforms.

**Comment by luboslenco** [comment]
Appears to be ok now using the latest kha.

**Comment by Disar** [comment]
Can confirm.
