### ISSUE TITLE
Allow multiple fonts (for things like bold, etc)?

### ISSUE THREAD

**Issue by hamaluik** [armory3d/zui#57]
It would be nice to be able to have some labels bolded or in different fonts (for example, headings).

**Comment by luboslenco** [comment]
Keeping the feature in "manual" mode for simplicity, but it is doable with something like this:
```haxe
ui.ops.font = myFont;
ui.text("Heading");
ui.ops.font = defaultFont;
ui.text("Content");
```
To adjust text size:
```haxe
ui.fontSize = 32;
ui.text("Big Text");
ui.fontSize = 18;
ui.text("Small Text");
```
