### ISSUE TITLE
Tooltip in multiple windows

### ISSUE THREAD

**Issue by jakelewis3d** [armory3d/zui#58]
Thank you for this useful and functional library.

I have noticed that when making use of multiple calls to zui.window the tooltips do not show.  I tracked this down to the line 
tooltipText = "";
 in the .window method.  I think this would be better performed in the begin() method, so that it is only called once per frame, not once per window.
Even with this fix, tooltips are only showing in the first window called.

Also, I was having issues with the window being blacked out which I tracked down to the globalG.color being switched within the drawTooltip() method. My overridden method simply stores the incoming globalG.color at the beginning of the method and restores it at the end.

Finally, if I could request that tooltips background and type colors be read from the Theme.

override function drawTooltip() {
		//do not call super
		var saveColor = globalG.color;  //jake
		globalG.color = 0xfffeff9c;//postit yellow. was  0xffefefef;
		var lines = tooltipText.split("\n");
		var tooltipW:Float = 0;
		for (line in lines) {
			var lineTooltipW = ops.font.width(fontSize, line);
			if (lineTooltipW > tooltipW) tooltipW = lineTooltipW;
		}
		tooltipX = Math.min(tooltipX, kha.System.windowWidth() - tooltipW - 20);
		globalG.fillRect(tooltipX, tooltipY, tooltipW + 20, ELEMENT_H() * lines.length * 0.6);
		globalG.font = ops.font;
		globalG.fontSize = fontSize;
		globalG.color = 0xff111111;
		for (i in 0...lines.length) {
			globalG.drawString(lines[i], tooltipX + 5, tooltipY + i * fontSize);
		}
		globalG.color = saveColor;  //jake
	}

**Comment by jakelewis3d** [comment]
Also, zui.text does not call the getHover() method, this was causing issues whereby the hovering over the previously called zui item would show the text item's tool tip.

I fixed it in my extended class with:
override public function text(text: String, align:Align = Left, bg = 0x00000000) {
		super.text(text, align, bg);
		getHover();
	}

**Comment by jakelewis3d** [comment]
Also,   drawCheck needs to use drawScaledImage in order to render the 'check' at the correct scale, for scaling of other than 1.0.

`function drawCheck(selected: Bool, hover: Bool) {
		var x = _x + checkOffsetX;
		var y = _y + checkOffsetY;

		g.color = hover ? t.ACCENT_HOVER_COL : t.ACCENT_COL;
		drawRect(g, t.FILL_ACCENT_BG, x, y, CHECK_SIZE(), CHECK_SIZE()); // Bg

		if (selected) { // Check
			g.color = kha.Color.White;
			//g.drawImage(checkSelectImage, x + checkSelectOffsetX, y + checkSelectOffsetY);
			g.drawScaledImage(checkSelectImage, x + checkSelectOffsetX, y + checkSelectOffsetY, checkSelectImage.width * SCALE, checkSelectImage.height * SCALE);  
			
	
		}
	}`

**Comment by luboslenco** [comment]
Seems to work for multiple windows now. Tooltip color is fetched from theme TEXT_COL and ACCENT_COL values. Other issues should be resolved as well.
