### ISSUE TITLE
Tab between input fields

### ISSUE THREAD

**Issue by FuzzyWuzzie** [armory3d/zui#59]
If I have several input fields in a row (or however), it would be nice to be able to tab between them (for example if I have 3 float fields in a row to denote a 3D position, and I want to type the coords in, it would be nice to type `0.0 <tab> 1.5 <tab> -0.3` instead of clicking on each field individually and then typing)

**Comment by luboslenco** [comment]
Some primitive tab switch is now in, for `textInput` and `slider`.
