### ISSUE TITLE
Float field initializes with handle text instead of handle value

### ISSUE THREAD

**Issue by hamaluik** [armory3d/zui#60]
Trying to use float field inputs:

```haxe
var x:Float = ui.floatInput(Id.handle({ value: 10.0 }), "x");
```

You get an empty input box, and the value of 10.0 isn't applied.

But if you use:

```haxe
var x:Float = ui.floatInput(Id.handle({ text: "10.0" }), "x");
```

Then it works as expected, though it is counter-intuitive to give a floating point value as text instead of its actual value.

**Comment by luboslenco** [comment]
Fixed in https://github.com/armory3d/zui/commit/e5118ec973581d03b71d5f943220e263317220e4 (and moved to `Ext.floatInput()`).
