### ISSUE TITLE
Backspace no longer working in TextInput field

### ISSUE THREAD

**Issue by jakelewis3d** [armory3d/zui#61]
Unless text is highlighted, the backspace key has no effect.

I tracked this down to the line

**text = text.substr(0, highlightStart) + text.substr(highlightEnd, text.length);**
which has no effect when highlightStart == highlightEnd, and this is often the case as just a few lines later
**setHighlight(cursorX, cursorX);** 
will indeed set them as equal.

I noticed that in your kode garden demo the backspace worked as expected in textinputs: [http://kodegarden.org/#23ae97114a4d60f249ce6054ba443c25e7264579](url)

I took the code from there and combined it with the erroneous line to produce:

**if (highlightStart == highlightEnd && highlightStart == cursorX) 
       text = text.substr(0, cursorX - 1) + text.substr(cursorX);   
else															 
       text = text.substr(0, highlightStart) + text.substr(highlightEnd, text.length);**

which seems to fix it.
Jake

**Comment by luboslenco** [comment]
Hm is this still an issue in latest zui? I recall having trouble with this as well but should be already patched here: https://github.com/armory3d/zui/commit/4060452f36ae7abed2356c8f0b0e508f45db36ea.

**Comment by sh-dave** [comment]
It should probably also be checked if it works with the latest input changes in Kha https://github.com/Kode/Kha/pull/772, https://github.com/Kode/Kha/pull/773, https://github.com/Kode/Kha/pull/779. The 772 PR f.ex. also prevented the use of function keys which is back now with 779. Not sure what other non-char keys might be affected.
