### ISSUE TITLE
Multiline TextInput / Text Area support?

### ISSUE THREAD

**Issue by Sondro** [armory3d/zui#62]
Hi, was going through the examples again, do you support multiline TextInput/text areas?

If not is there a roadmap for when it would be added?

It looks like img ui supports it: https://github.com/ocornut/imgui/search?utf8=%E2%9C%93&q=multiline&type=

**Comment by luboslenco** [comment]
Hello. Not supported yet but will get to it eventually. PR welcome.:)

**Comment by Sondro** [comment]
Hi, I started working on the textInputMulti for a bit yesterday and got it drawn and placed properly in scale.

The general idea is to have a fixed lines num and/or grow = true and have the panel update and use it's scrollbar (since there isn't much room to attache a bar elsewhere). Then maybe glue scrolling panels onto other panels later.

Anyways, I ran into a lot of buggy performance with scrollbars disappearing, labels popping and flying off, input spamming, and other stuff that is from zui.

I tried to document the issues and post an example here (def not PR ready):

https://github.com/Sondro/zux

**Comment by Sondro** [comment]
Whoops, I made too many copies of zux (wip zui) and I lost the latest one.  Just updated the repo with one that works better, but the scale is not working in this one. Sorry about that.

**Comment by ImmanuelSamuel** [comment]
Really need this feature for an RPG type game I am developing. Need some multi-line text support for mission details.

**Comment by BlackGoku36** [comment]
Any update on getting it implemeted?

**Comment by mundusnine** [comment]
@BlackGoku36 it's implemented in this [pull request](https://github.com/armory3d/zui/pull/73)

**Comment by luboslenco** [comment]
See https://github.com/armory3d/zui/pull/73#issuecomment-579209352.
