### ISSUE TITLE
Is there a way to force redraw without needing to keep setting redraw?

### ISSUE THREAD

**Issue by Jarrio** [armory3d/zui#64]
I'm currently formatting my document like the following:
```haxe
class Foo {
    public var ui:Zui;
    public var window_a = new Handle();
    public var window_b = new Handle();
    //....
    public function render(graphics) {
        this.window_a.redraws = 2;
        this.window_b.redraws = 2;        
    }
}
```

If I don't set redraw outside of the render loop it doesn't update frequently enough (eg in the class constructor). Is there a "correct way" to do this?

If not, I could add an `alwaysUpdate` bool to `Handle` and just have it reset draws to `2`.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/zui/pull/65.
