### ISSUE TITLE
combo content detaches when scrolling the window via mousewheel

### ISSUE THREAD

**Issue by sh-dave** [armory3d/zui#68]
- create so much ui that you get a scrollable window
- create a `zui.combo` element
- click the `combo` to open it
- scroll via mousewheel
- the combo scrolls up correctly, but it's content stays in place where it was opened

![image](https://user-images.githubusercontent.com/13007175/41962126-87b2b6a2-79f4-11e8-8d61-9ccae392254f.png)

**Comment by luboslenco** [comment]
It looks like nowadays window scroll is blocked while combo is opened, so perhaps this is no longer an issue.

**Comment by sh-dave** [comment]
With `Zui.alwaysRedraw = true;` it still won't work. But i need that flag enabled to update counter displays and such.

**Comment by luboslenco** [comment]
Aha yes, I see it now, thanks for info!

**Comment by sh-dave** [comment]
fixed in af2371a733da3dc788374f18b9c8b3fd4f81d0cc
