### ISSUE TITLE
Zui.hx:14: characters 10-27 : Type not found : zui.Themes

### ISSUE THREAD

**Issue by HipsterPhD** [armory3d/zui#78]
Just pulled the repo this morning and received the aforementioned error. There were also issues with adding the library to a Kha project via cloning to `Libraries`  as well as via `haxelib` (`project.addLibrary('zui')` is currently in my `khafile.js`); I am not sure if these issues are related. I am new to Haxe, Kha and ZUI in general so if I made a rookie mistake please let me know!
![capture](https://user-images.githubusercontent.com/43857463/49157366-a25d6200-f2ed-11e8-8e7b-790909470229.PNG)

**Comment by sh-dave** [comment]
Your directory layout is wrong, you need to have the whole zui repo in `Libraries`, not just the `zui/Sources/zui` folder.

**Comment by HipsterPhD** [comment]
> Your directory layout is wrong, you need to have the whole zui repo in `Libraries`, not just the `zui/Sources/zui` folder.

Thanks for your help; when I did that initially, I was getting an error when trying to import `zui.*` but now it works!
