### ISSUE TITLE
Menu Bar?

### ISSUE THREAD

**Issue by lunabunn** [armory3d/zui#79]
Does zui have built-in menu bars? (like that of imgui?)
This seems like a really basic thing, but I can't find it in the examples nor in the README.

For clarification, I mean the bar at the top of many programs with drop-down menu items like "File", "Edit", "View", etc.

If this is not yet implemented, what can I do to mimic it? Is it planned to be added in the near feature?

Thanks in advance,

**Comment by luboslenco** [comment]
Hello,

No built-in menu bar yet. There is a plan to eventually add it into `Ext.hx`, but I am not sure when exactly. Right now I mimic it with `button()`s. :)

**Comment by mundusnine** [comment]
If anyone is wondering how lubos does it, have a look [here](https://github.com/armory3d/armorpaint/blob/master/Sources/arm/ui/UIMenu.hx#L41)

**Comment by mundusnine** [comment]
@luboslenco you added the stubs for menu's so this should probably be close no ?

**Comment by luboslenco** [comment]
Working on it but it's not finished yet.

**Comment by luboslenco** [comment]
Still mimicked by buttons. :)
