### ISSUE TITLE
[bug]Latest kha throws g2.begin "throw "End before you begin"

### ISSUE THREAD

**Issue by Disar** [armory3d/zui#81]
As title says.

Happens in `Zui.hx` line 190:

```haxe
	function bakeElements() {
		if (checkSelectImage != null) {
			checkSelectImage.unload();
		}
		checkSelectImage = kha.Image.createRenderTarget(Std.int(CHECK_SELECT_SIZE()), Std.int(CHECK_SELECT_SIZE()), null, NoDepthAndStencil, 1, ops.khaWindowId);
		var g = checkSelectImage.g2;
		g.begin(true, 0x00000000); //<--------here
....
	}
```

**Comment by luboslenco** [comment]
I pushed some fixes, maybe that helps. If not, do you get any other errors before it falls into the "End before you begin" loop?

**Comment by Disar** [comment]
I guess it happens because I assumed that zui doesn't actually need a g2.begin call. But I realise that in the readme you close any g2 call before calling zui.

My bad.
