### ISSUE TITLE
UIElements  a subsequent version of IMGUI 

### ISSUE THREAD

**Issue by longde123** [armory3d/zui#82]
UIElements is a Unity UI framework, which is a subsequent version of IMGUI for UI construction in editor extensions.

https://docs.unity3d.com/Manual/UIElements.html

**Comment by longde123** [comment]
zui +DomKit magic can it produce?
DomKit
CSS Components based strictly typed UI framework for Haxe
https://github.com/HeapsIO/domkit

**Comment by luboslenco** [comment]
Would be cool, keeping an eye on DomKit! 🙂
