### ISSUE TITLE
How to contribute ?

### ISSUE THREAD

**Issue by melMass** [armory3d/zui#84]
Hi @luboslenco ,

Thanks a lot for Iron, Armory and Zui.
I'm learning Haxe thanks to your projects.

I wanted to know if there is a prefered way of contributing to Zui ? Do you think it should stay as simple and streamlined as it is or are you open to improvements?

For now, I rely on Static Extensions to avoid touching to Zui source and this is what I added:

- Box Selection
- Clicking outside a node unselect it
- Autolayout
...

But for instance I wanted to change the hardcoded label color for the nodes, I think this is not possible without touching Zui directly.  As I did not wrap my head around Iron (everything is a Trait ?) I'm not sure of your approach for ArmoryPaint, but it seems you added all of that in `arm` ?

**Comment by luboslenco** [comment]
Hello @melMass, thanks for your hearth-warming message!

Sounds like great stuff! I am trying to prevent myself from adding more stuff into the core Zui classes, however extending `Ext.hx` (when possible) with more functionality is always appreciated. For things like hardcoded node colors - we should address that directly and make it read some theme color. 🙂

**Comment by melMass** [comment]
Thanks.
I'll make a pull request adding theme variables where needed and we can continue the discussion there !
