### ISSUE TITLE
[REQUEST] draggable ui sections

### ISSUE THREAD

**Issue by lewislepton** [armory3d/zui#9]
aye... it would be cool if you could drag the nest of ui elements around

**Comment by luboslenco** [comment]
Absolutely, will do!

**Comment by lewislepton** [comment]
cool spot ;)

**Comment by jefvel** [comment]
I guess this would be best to have in the zui.window function? like add one more parameter named draggable?

**Comment by luboslenco** [comment]
@jefvel Yup, zui.window() would probably be a good place:)

**Comment by 5Mixer** [comment]
Hello! Any news about this? It seems like there hasn't been a commit in a little while, but I'd love to use zui in my project and being able to move/resize windows would be super helpful.

**Comment by luboslenco** [comment]
Unfortunately still no news on this yet, but hopefully more updates soon.

**Comment by luboslenco** [comment]
Windows are now draggable:
`ui.window(Id.handle(), x, y, w, h, draggable);`

Beware of the api changes in the latest update, added notice to the readme.md file.

**Comment by 5Mixer** [comment]
Thanks @luboslenco, can't wait to try this out. 👍
