### ISSUE TITLE
[Bug] Canvas button doesn't respect height

### ISSUE THREAD

**Issue by BlackGoku36** [armory3d/zui#93]
When you add more height to canvas button than default height, hovering over this new height are make button unclickable

Try canvas example for reproducing bug

Edit: setting `ELEMENT_H` to element's height works, but setting `BUTTON_H` do not work.

**Comment by luboslenco** [comment]
Thanks for report - fix at https://github.com/armory3d/zui/commit/c89f9eb29eb18ea2952759094f83288769d9df0a.
