### ISSUE TITLE
[FR] Child to respect parent's size and rotation - Canvas

### ISSUE THREAD

**Issue by BlackGoku36** [armory3d/zui#94]
~~When parent element's height and width is change, child height and width remain the same.~~
~~Can be tested with canvas example or armory2d~~
When parent element's size and rotation is changed, children should adapt to these change

**Comment by MoritzBrueckner** [comment]
I think this isn't really a bug, maybe we should let the user decide what each parent should "copy", for example with checkboxes in Armory2D for location, rotation and scale (everything pre-selected?). What do you think?

**Comment by BlackGoku36** [comment]
> I don't think this is a bug, it's more like a missing feature.

Yeah, you are right

> Maybe we should let the user decide what attributes each parent should influence, for example with checkboxes in Armory2D for location, rotation and scale (everything pre-selected?). What do you think?

Cool!

**Comment by luboslenco** [comment]
Rotation seems to work now. Size is not inherited, but I think that could be handled directly in armory2d when scaling the element (since there is multiple possible ways on how that could behave).
