### ISSUE TITLE
[FR] Emojis and glyphs?

### ISSUE THREAD

**Issue by BlackGoku36** [armory3d/zui#96]
Is it possible to do emoji or glyphs?

**Comment by luboslenco** [comment]
Should be doable by including the code points you need in the `kha.graphics2.Graphics.fontGlyphs` array. Afterwards, Kha will re-create the font bitmap containing all the specified unicode characters.

https://github.com/Kode/Kha/blob/master/Sources/kha/graphics2/Graphics.hx#L141
https://github.com/Kode/Kha/blob/master/Sources/kha/graphics2/truetype/StbTruetype.hx
