### ISSUE TITLE
Nodes going window xp error on Krom

### ISSUE THREAD

**Issue by BlackGoku36** [armory3d/zui#97]
![Screen-Recording-2019-12-11-at-12 37 30-AM](https://user-images.githubusercontent.com/36535717/70560800-3fb0ce80-1baf-11ea-8cf2-c3db3c5a1ec1.gif)
Above happen only on krom, works fine on html5
Kha and krom taken from [Kode](https://github.com/Kode)

Edit: Happen on native too (MacOS)

**Comment by luboslenco** [comment]
Sorry but I am unable to reproduce, I tested with latest Kha + Krom from Kode using the provided [Nodes](https://github.com/armory3d/zui/tree/master/examples/Nodes) example on Windows 10.

**Comment by BlackGoku36** [comment]
I guess, it is again MacOS + Metal bug. Will have to switch back to older version of krom(lastest have error when trying to use opengl) and use opengl

**Comment by luboslenco** [comment]
Will do my best to send more Metal pull-requests into Kinc, so we can abandon opengl. Robert already started updating the krafix shader compiler, once that is finished it should  hopefully handle all of the armory shaders so I can focus more on Metal. 🙂
